using System.Drawing;
using System.Security.Claims;
using IBS.DataAccess.Repository.IRepository;
using IBS.Models.Common;
using IBS.Models.MasterFile;
using IBS.Utility.Helpers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using OfficeOpenXml.Style;

namespace IBSWeb.Areas.User.Controllers
{
    [Area(nameof(User))]
    public class MasterFileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<MasterFileController> _logger;

        public MasterFileController(
            UserManager<ApplicationUser> userManager,
            IUnitOfWork unitOfWork,
            ILogger<MasterFileController> logger)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }

        #region -- Helper Methods --

        private string GetUserFullName()
        {
            return User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.GivenName)?.Value
                   ?? User.Identity?.Name!;
        }

        private async Task<string?> GetCompanyClaimAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null) return null;

            var claims = await _userManager.GetClaimsAsync(user);
            return claims.FirstOrDefault(c => c.Type == "Company")?.Value;
        }

        #endregion

        #region -- Main Excel Generation Method --

        [HttpGet]
        public async Task<IActionResult> GenerateExcel(string masterFileType, CancellationToken cancellationToken)
        {
            try
            {
                var extractedBy = GetUserFullName();
                var companyClaims = await GetCompanyClaimAsync();

                if (companyClaims == null)
                {
                    return BadRequest("Company claim not found");
                }

                // Generate Excel based on master file type
                var result = masterFileType.ToLower() switch
                {
                    "customer" => await GenerateCustomerExcel(extractedBy, companyClaims, cancellationToken),
                    "supplier" => await GenerateSupplierExcel(extractedBy, companyClaims, cancellationToken),
                    "bankaccount" => await GenerateBankAccountExcel(extractedBy, companyClaims, cancellationToken),
                    "service" => await GenerateServiceExcel(extractedBy, companyClaims, cancellationToken),
                    "employee" => await GenerateEmployeeExcel(extractedBy, companyClaims, cancellationToken),
                    _ => throw new ArgumentException($"Invalid master file type: {masterFileType}")
                };

                if (result.stream == null)
                {
                    TempData["info"] = "No Record Found";
                    return RedirectToAction("Index", "Home");
                }

                // Audit Trail
                AuditTrail auditTrail = new(
                    extractedBy,
                    $"Generate {masterFileType} master file excel",
                    $"{masterFileType}",
                    companyClaims
                );
                await _unitOfWork.FilprideAuditTrail.AddAsync(auditTrail, cancellationToken);
                await _unitOfWork.SaveAsync(cancellationToken);

                return File(result.stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", result.fileName);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                // Sanitize masterFileType to prevent log forging
                var safeMasterFileTypeForLog = masterFileType?
                    .Replace("\r", " ")
                    .Replace("\n", " ");
                _logger.LogError(ex, "Failed to generate {MasterFileType} master file excel. Error: {ErrorMessage}, Stack: {StackTrace}. Generated by: {UserName}",
                    safeMasterFileTypeForLog, ex.Message, ex.StackTrace, _userManager.GetUserName(User));
                return RedirectToAction("Index", "Home");
            }
        }

        #endregion

        #region -- Customer Master File --

        private async Task<(MemoryStream? stream, string fileName)> GenerateCustomerExcel(
            string extractedBy,
            string company,
            CancellationToken cancellationToken)
        {
            // Fetch customers
            var customers = (await _unitOfWork.FilprideCustomer
                .GetAllAsync(c => c.Company == company, cancellationToken))
                .OrderBy(x => x.CustomerCode);

            if (!customers.Any())
            {
                return (null, string.Empty);
            }

            // Fetch all customer IDs for this company
            var customerIds = customers.Select(c => c.CustomerId).ToList();

            // Fetch branches separately
            var branches = await _unitOfWork.FilprideCustomerBranch.GetAllAsync(
                filter: b => customerIds.Contains(b.CustomerId),
                cancellationToken: cancellationToken);

            // Create Excel package
            using var package = new ExcelPackage();

            // ===== WORKSHEET 1: Customer Master File =====
            var customerColumns = new List<ColumnDefinition>
            {
                new() { Header = "CUSTOMER CODE", ValueSelector = c => ((Customer)c).CustomerCode ?? "" },
                new() { Header = "CUSTOMER NAME", ValueSelector = c => ((Customer)c).CustomerName },
                new() { Header = "CUSTOMER ADDRESS", ValueSelector = c => ((Customer)c).CustomerAddress },
                new() { Header = "TIN NO", ValueSelector = c => ((Customer)c).CustomerTin },
                new() { Header = "BUSINESS STYLE", ValueSelector = c => ((Customer)c).BusinessStyle ?? "" },
                new() { Header = "ZIP CODE", ValueSelector = c => ((Customer)c).ZipCode ?? "" },
                new() { Header = "CREDIT TERM", ValueSelector = c => ((Customer)c).CustomerTerms },
                new()
            {
                Header = "CREDIT LIMIT",
                ValueSelector = c => ((Customer)c).CreditLimit,
                NumberFormat = "#,##0.00",
                Alignment = ExcelHorizontalAlignment.Right
            },
            new()
            {
                Header = "CREDIT LIMIT AS OF TODAY",
                ValueSelector = c => ((Customer)c).CreditLimitAsOfToday,
                NumberFormat = "#,##0.00",
                Alignment = ExcelHorizontalAlignment.Right
            },
            new() { Header = "STATION CODE", ValueSelector = c => ((Customer)c).StationCode ?? "" },
            new() { Header = "TYPE", ValueSelector = c => ((Customer)c).Type },
            new() { Header = "DEFAULT COMMISION RATE", ValueSelector = c => ((Customer)c).CommissionRate },
            new() { Header = "DEFAULT COMMISIONEE", ValueSelector = c => ((Customer)c).Commissionee?.SupplierName ?? ""},
            new() { Header = "STATUS", ValueSelector = c => ((Customer)c).IsActive ? "Active" : "Inactive" },
            };

            var customerWidths = new Dictionary<string, double>
            {
                { "CUSTOMER CODE", 20 },
                { "CUSTOMER NAME", 70 },
                { "CUSTOMER ADDRESS", 100 },
                { "BUSINESS STYLE", 50 }
            };

            // Build customer worksheet
            BuildWorksheet(
                package,
                customers,
                "Customer",
                "CUSTOMER MASTER FILE",
                extractedBy,
                company,
                customerColumns,
                customerWidths,
                2
            );

            // ===== WORKSHEET 2: Customer Branches =====
            if (branches.Any())
            {
                var branchColumns = new List<ColumnDefinition>
                {
                    new() { Header = "CUSTOMER NAME", ValueSelector = b => ((CustomerBranch)b).Customer?.CustomerName},
                    new() { Header = "BRANCH NAME", ValueSelector = b => ((CustomerBranch)b).BranchName },
                    new() { Header = "BRANCH ADDRESS", ValueSelector = b => ((CustomerBranch)b).BranchAddress  },
                };

                var branchWidths = new Dictionary<string, double>
                {
                    { "CUSTOMER NAME", 30 },
                    { "BRANCH NAME", 30 },
                    { "BRANCH ADDRESS", 100 }
                };

                BuildWorksheet(
                    package,
                    branches.Cast<object>().ToList(),
                    "Branches",
                    "CUSTOMER BRANCHES",
                    extractedBy,
                    company,
                    branchColumns,
                    branchWidths,
                    2
                );
            }

            // Save and return
            var fileName = $"Customer_MasterFile_{DateTimeHelper.GetCurrentPhilippineTime():yyyyMMddHHmmss}.xlsx";
            var stream = new MemoryStream();
            await package.SaveAsAsync(stream, cancellationToken);
            stream.Position = 0;

            return (stream, fileName);
        }

        #endregion

        #region -- Supplier Master File --

        private async Task<(MemoryStream? stream, string fileName)> GenerateSupplierExcel(
                   string extractedBy,
                   string company,
                   CancellationToken cancellationToken)
        {
            var suppliers = (await _unitOfWork.FilprideSupplier
                    .GetAllAsync(s => s.Company == company, cancellationToken))
                .OrderBy(x => x.SupplierCode);

            if (!suppliers.Any())
            {
                return (null, string.Empty);
            }

            var columns = new List<ColumnDefinition>
            {
                new() { Header = "SUPPLIER CODE", ValueSelector = s => ((Supplier)s).SupplierCode ?? "" },
                new() { Header = "SUPPLIER NAME", ValueSelector = s => ((Supplier)s).SupplierName },
                new() { Header = "SUPPLIER ADDRESS", ValueSelector = s => ((Supplier)s).SupplierAddress },
                new() { Header = "ZIP CODE", ValueSelector = s => ((Supplier)s).ZipCode },
                new() { Header = "BRANCH", ValueSelector = s => ((Supplier)s).Branch },
                new() { Header = "TIN NO", ValueSelector = s => ((Supplier)s).SupplierTin },
                new() { Header = "CREDIT TERMS", ValueSelector = s => ((Supplier)s).SupplierTerms },
                new() { Header = "VATABLE", ValueSelector = s => ((Supplier)s).VatType },
                new() { Header = "TAXABLE", ValueSelector = s => ((Supplier)s).TaxType },
                new() { Header = "CATEGORY", ValueSelector = s => ((Supplier)s).Category },
                new() { Header = "EWT RATE", ValueSelector = s => ((Supplier)s).WithholdingTaxPercent * 100 }
            };

            var customWidths = new Dictionary<string, double>
            {
                { "SUPPLIER NAME", 60 },
                { "SUPPLIER ADDRESS", 120 }

            };

            return await BuildExcelFile(
                suppliers,
                "Suppliers",
                "Supplier_MasterFile",
                extractedBy,
                company,
                columns,
                customWidths,
                2,
                cancellationToken
            );
        }
        #endregion

        #region -- Bank Account Master File --
        private async Task<(MemoryStream? stream, string fileName)> GenerateBankAccountExcel(
            string extractedBy,
            string company,
            CancellationToken cancellationToken)
        {
            var bankAccounts = (await _unitOfWork.FilprideBankAccount.GetAllAsync(
                filter: b => b.Company == company,
                cancellationToken: cancellationToken))
                .OrderBy(x => x.AccountNo);

            if (!bankAccounts.Any())
            {
                return (null, string.Empty);
            }

            var columns = new List<ColumnDefinition>
            {
                new() { Header = "ACCOUNT NO", ValueSelector = b => ((BankAccount)b).AccountNo },
                new() { Header = "ACCOUNT NAME", ValueSelector = b => ((BankAccount)b).AccountName },
                new() { Header = "BANK", ValueSelector = b => ((BankAccount)b).Bank },
                new() { Header = "BRANCH", ValueSelector = b => ((BankAccount)b).Branch },
            };

            var customWidths = new Dictionary<string, double>
            {
                { "ACCOUNT NAME", 40 },
                { "BRANCH", 80 }
            };

            return await BuildExcelFile(
                bankAccounts,
                "Bank Accounts",
                "BankAccount_MasterFile",
                extractedBy,
                company,
                columns,
                customWidths,
                2,
                cancellationToken
            );
        }

        #endregion

        #region -- Service Master File --
        private async Task<(MemoryStream? stream, string fileName)> GenerateServiceExcel(
            string extractedBy,
            string company,
            CancellationToken cancellationToken)
        {
            var services = (await _unitOfWork.FilprideService.GetAllAsync(
                cancellationToken: cancellationToken))
                .OrderBy(x => x.ServiceNo);

            if (!services.Any())
            {
                return (null, string.Empty);
            }

            var columns = new List<ColumnDefinition>
            {
                new() { Header = "SERVICE NO", ValueSelector = s => ((Service)s).ServiceNo },
                new() { Header = "SERVICE NAME", ValueSelector = s => ((Service)s).Name },
                new() { Header = "PERCENT", ValueSelector = s => ((Service)s).Percent},
            };

            var customWidths = new Dictionary<string, double>
            {
                { "SERVICE NAME", 30 },
            };

            return await BuildExcelFile(
                services,
                "Services",
                "Service_MasterFile",
                extractedBy,
                company,
                columns,
                customWidths,
                2,
                cancellationToken
            );
        }

        #endregion

        #region -- Employee Master File --
        private async Task<(MemoryStream? stream, string fileName)> GenerateEmployeeExcel(
            string extractedBy,
            string company,
            CancellationToken cancellationToken)
        {

            var employees = (await _unitOfWork.FilprideEmployee
                .GetAllAsync(x => x.Company == company, cancellationToken))
                .OrderBy(x => x.EmployeeNumber);

            if (!employees.Any())
            {
                return (null, string.Empty);
            }

            var columns = new List<ColumnDefinition>
            {
                new() { Header = "EMPLOYEE NO", ValueSelector = e => ((Employee)e).EmployeeNumber },
                new() { Header = "FIRST NAME", ValueSelector = e => ((Employee)e).FirstName },
                new() { Header = "MIDDLE NAME", ValueSelector = e => ((Employee)e).MiddleName },
                new() { Header = "LAST NAME", ValueSelector = e => ((Employee)e).LastName },
                new() { Header = "ADDRESS", ValueSelector = e => ((Employee)e).Address },
                new() { Header = "BIRTH DATE", ValueSelector = e => ((Employee)e).BirthDate, NumberFormat = "mm/dd/yyyy" },
                new() { Header = "TEL NO", ValueSelector = e => ((Employee)e).TelNo },
                new() { Header = "SSS NO", ValueSelector = e => ((Employee)e).SssNo },
                new() { Header = "TIN NO", ValueSelector = e => ((Employee)e).TinNo },
                new() { Header = "PHILHEALTH NO", ValueSelector = e => ((Employee)e).PhilhealthNo },
                new() { Header = "PAGIBIG NO", ValueSelector = e => ((Employee)e).PagibigNo },
                new() { Header = "COMPANY", ValueSelector = e => ((Employee)e).Company },
                new() { Header = "DEPARTMENT", ValueSelector = e => ((Employee)e).Department },
                new() { Header = "DATE HIRED", ValueSelector = e => ((Employee)e).DateHired, NumberFormat = "mm/dd/yyyy" },
                new() { Header = "DATE RESIGNED", ValueSelector = e => ((Employee)e).DateResigned?.ToDateTime(TimeOnly.MinValue), NumberFormat = "mm/dd/yyyy" },
                new() { Header = "POSITION", ValueSelector = e => ((Employee)e).Position },
                new() { Header = "IS MANAGERIAL", ValueSelector = e => ((Employee)e).IsManagerial ? "Yes" : "No" },
                new() { Header = "SUPERVISOR", ValueSelector = e => ((Employee)e).Supervisor },
            };

            var customWidths = new Dictionary<string, double>
            {
                { "SERVICE NAME", 30 },
                { "ADDRESS", 100},
                { "PHILHEALTH NO", 40 },
            };

            return await BuildExcelFile(
                employees,
                "Employees",
                "Employee_MasterFile",
                extractedBy,
                company,
                columns,
                customWidths,
                2,
                cancellationToken
            );
        }
        #endregion


        #region -- Core Excel Building Logic --

        private void BuildWorksheet<T>(
            ExcelPackage package,
            IEnumerable<T> data,
            string worksheetName,
            string reportTitle,
            string extractedBy,
            string company,
            List<ColumnDefinition> columns,
            Dictionary<string, double>? customColumnWidths,
            int freezeAtColumn) where T : class
        {
            var worksheet = package.Workbook.Worksheets.Add(worksheetName);

            // Set report title
            var titleRange = worksheet.Cells["A1:B1"];
            titleRange.Merge = true;
            titleRange.Value = reportTitle;
            titleRange.Merge = true;
            titleRange.Style.Font.Size = 13;
            titleRange.Style.Font.Bold = true;

            // Set metadata
            worksheet.Cells["A2"].Value = "Extracted By: ";
            worksheet.Cells["B2"].Value = extractedBy;
            worksheet.Cells["A3"].Value = "Company: ";
            worksheet.Cells["B3"].Value = company;
            worksheet.Cells["A4"].Value = "Date Generated: ";
            worksheet.Cells["B4"].Value = DateTimeHelper.GetCurrentPhilippineTime();
            worksheet.Cells["B4"].Style.Numberformat.Format = "mm/dd/yyyy";
            worksheet.Cells["B4"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;

            // Set column headers (Row 6)
            int headerRow = 6;
            int columnCount = columns.Count;

            for (int i = 0; i < columnCount; i++)
            {
                worksheet.Cells[headerRow, i + 1].Value = columns[i].Header;
            }

            // Apply styling to the header row
            using (var range = worksheet.Cells[headerRow, 1, headerRow, columnCount])
            {
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(Color.LightGray);
                range.Style.Font.Bold = true;
                range.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                range.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
            }

            // Populate data rows
            int row = headerRow + 1;
            foreach (var item in data)
            {
                for (int col = 0; col < columnCount; col++)
                {
                    var columnDef = columns[col];
                    var cellValue = columnDef.ValueSelector(item);
                    var cell = worksheet.Cells[row, col + 1];

                    cell.Value = cellValue;

                    if (!string.IsNullOrEmpty(columnDef.NumberFormat))
                    {
                        cell.Style.Numberformat.Format = columnDef.NumberFormat;
                    }

                    cell.Style.HorizontalAlignment = columnDef.Alignment;
                }
                row++;
            }

            // Auto-fit columns
            worksheet.Cells.AutoFitColumns();

            // Apply custom column widths if specified
            if (customColumnWidths != null)
            {
                foreach (var width in customColumnWidths)
                {
                    var colIndex = columns.FindIndex(c => c.Header == width.Key) + 1;
                    if (colIndex > 0)
                    {
                        worksheet.Column(colIndex).Width = width.Value;
                    }
                }
            }

            // Freeze panes
            worksheet.View.FreezePanes(headerRow + 1, freezeAtColumn);

            // Apply borders to all data
            if (row > headerRow + 1)
            {
                using (var range = worksheet.Cells[headerRow, 1, row - 1, columnCount])
                {
                    range.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    range.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    range.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    range.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                }
            }
        }

        private async Task<(MemoryStream stream, string fileName)> BuildExcelFile<T>(
            IEnumerable<T> data,
            string reportTitle,
            string fileNamePrefix,
            string extractedBy,
            string company,
            List<ColumnDefinition> columns,
            Dictionary<string, double>? customColumnWidths,
            int freezeAtColumn,
            CancellationToken cancellationToken) where T : class
        {
            using var package = new ExcelPackage();

            BuildWorksheet(
                package,
                data,
                reportTitle.Replace(" ", ""),
                reportTitle.ToUpper(),
                extractedBy,
                company,
                columns,
                customColumnWidths,
                freezeAtColumn
            );

            var fileName = $"{fileNamePrefix}_{DateTimeHelper.GetCurrentPhilippineTime():yyyyMMddHHmmss}.xlsx";
            var stream = new MemoryStream();
            await package.SaveAsAsync(stream, cancellationToken);
            stream.Position = 0;

            return (stream, fileName);
        }

        #endregion

        #region -- Column Definition Helper Class --

        private class ColumnDefinition
        {
            public string Header { get; set; } = string.Empty;
            public Func<object, object?> ValueSelector { get; set; } = null!;
            public string? NumberFormat { get; set; }
            public bool WrapText { get; set; }
            public ExcelHorizontalAlignment Alignment { get; set; } = ExcelHorizontalAlignment.Left;
        }

        #endregion
    }
}
